[workspace]
resolver = "2"

members = [
    "grus_codegen",
    "grus_module",
]

[workspace.dependencies]
grus_codegen = { path = "grus_codegen", default-features = false }
grus_module = { path = "grus_module", default-features = false }
