[package]
name = "grus_module"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]


object = "0.36.7"

cranelift-module = "0.116.1"
cranelift-object = "0.116.1"
cranelift-codegen = "0.116.1"

