[package]
name = "grus_module"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]

memmap = "0.7.0"

object = {workspace = true}

cranelift-module = "0.116.1"
cranelift-object = "0.116.1"
cranelift-codegen = "0.116.1"


anyhow = {workspace=true}
