[package]
name = "grus_codegen"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
#cranelift-codegen = {git = 'https://github.com/iwanders/wasmtime', features=["x86", "arm64"], rev="8cb032a81de689b90c4398355cc2a719aa487a09"}
#cranelift-codegen = {version="0.116.1", features=["x86", "arm64"]}
cranelift-codegen = {path="../../../bytecodealliance/wasmtime/cranelift/codegen", features=["x86", "arm64"]}
target-lexicon = {version="0.13.1"}
cranelift-reader = {path="../../../bytecodealliance/wasmtime/cranelift/reader"}
cranelift-jit = {path="../../../bytecodealliance/wasmtime/cranelift/jit"}
cranelift-module = {path="../../../bytecodealliance/wasmtime/cranelift/module"}
cranelift-native = {path="../../../bytecodealliance/wasmtime/cranelift/native"}
cranelift-object = {path="../../../bytecodealliance/wasmtime/cranelift/object"}


